### PR TITLE
Rename osc to os as that is the name in OS 0.6 onwards.

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by jimmidyson** [comment]
ok to test

**Comment by christian-posta** [comment]
Actually @davsclaus the command line tool was renamed to `oc` not `os` :)

**Comment by davsclaus** [comment]
@christian-posta ah darn what a crappy name, open crap? open confusing name here or open cube?

**Comment by jimmidyson** [comment]
Oops! I even reviewed this one ;)

**Comment by davsclaus** [comment]
@christian-posta fancy doing a PR ? I just mess up and name it something else again

**Comment by christian-posta** [comment]
sure, on its way

**Comment by jimmidyson** [comment]
The rename happened to stop conflict with existing CLI tool called osc. I assume it means OpenShift CLI... but yeah crap name.

**Comment by christian-posta** [comment]
here it is: https://github.com/fabric8io/quickstarts/pull/508

**Pull request closed without merging**
