### PR TITLE
Added karaf4 camel-log archetype

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by davsclaus** [comment]
I do not see any thing karaf 4 specific about this? What is the different with this and the existing karaf log quickstart?

**Comment by dhirajsb** [comment]
@davsclaus this quickstart uses the new karaf4 maven plugin to create a custom distro that only has the karaf bits needed by the application, it doesn't rely on a pre-baked karaf install, which might have bits that are not needed. For example, this demo doesn't include shell or ssh features. Also, since the application bundle is included as a boot bundle, there is no need to create an application feature just to load a single bundle route.

**Comment by davsclaus** [comment]
Ah @dhirajsb that is really cool, great to hear and see karaf 4 making great progress towards micro services and container world. Welcome to fabric8 v2 ;)

**Comment by dhirajsb** [comment]
@davsclaus btw, to support lean karaf4 deployment of camel routes without karaf camel commands, we need to fix [CAMEL-9039](https://issues.apache.org/jira/browse/CAMEL-9039)

**Pull request merged**
