### PR TITLE
Fixes #576 Upgrade Docker Maven Plugin to 0.13.0

### LINKED ISSUE #576: Upgrade Docker Maven Plugin to 0.13.0
Hi,

as stated in this issue:

https://github.com/fabric8io/fabric8/issues/4400

We need to upgrade Docker Maven Plugin also in quickstarts project.

I'll take care of this issue.

Andrea

### PR DESCRIPTION
**Pull request by oscerd**
Hi.

This PR fixes #576.

Andrea

### CODE REVIEW

**Comment by davsclaus** [comment]
Oh sorry @oscerd the docker plugin must be set in each maven module as they are currently. The reason is that those quickstarts each becomes a maven archetype and maven does not allow to inherit properties for its plugins you use (only dependencies etc). 

Do you mind changing the PR to be like today but essentially upgrade the version in each of them.

**Comment by oscerd** [comment]
No problema Claus :-) i'll change the pr this evening :-)
Il 07/lug/2015 18:35, "Claus Ibsen" <notifications@github.com> ha scritto:

**Comment by oscerd** [comment]
I've bring back the repository to the original situation and looking at #579 by @jstrachan I've updated just the quickstart projects POM.

I've also noticed that in some POM there wasn't the docker.maven.plugin.version property, so I've added it.

Andrea

**Comment by oscerd** [comment]
Let me know if this is ok :-)

**Comment by davsclaus** [comment]
ok to test

**Pull request merged**
